server.servlet.context-path=/dict-group
server.port=9095



logging.level.tracer=TRACE

tp_alarm_event_addr=./data\tp_alarm_event_202604021206.xlsx
jh_alarm_event_addr=./data\聚合数据 2(2).xlsx

kafka.addr=localhost:9092
kafka.topic=alarm_message
kafka.config=


